export const page: string;
export const wrapper: string;
export const inner: string;
export const login: string;
export const indicator: string;
export const logoImage: string;
export const footer: string;
export const languageText: string;
export const privacyText: string;
